spring:
  application:
    name: ai_engine
  autoconfigure:
    exclude:
      - org.springframework.ai.model.chat.memory.repository.jdbc.autoconfigure.JdbcChatMemoryRepositoryAutoConfiguration
      - org.springframework.ai.model.chat.memory.autoconfigure.ChatMemoryAutoConfiguration
  jpa:
    open-in-view: false