version: '3.8'

services:
    postgres-master:
        image: postgres:17
        container_name: postgres-master
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: mydb
            POSTGRES_HOST_AUTH_METHOD: "scram-sha-256

                host replication all 0.0.0.0/0 md5"
            POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
        ports:
            - "5532:5432"
        volumes:
            - postgres-master-data:/var/lib/postgresql/data
            - ./master/postgresql.conf:/etc/postgresql/postgresql.conf
            - ./master/pg_hba.conf:/etc/postgresql/pg_hba.conf
            - ./master/init.sql:/docker-entrypoint-initdb.d/init.sql
        command: postgres -c config_file=/etc/postgresql/postgresql.conf
        networks:
            - postgres-network
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres" ]
            interval: 10s
            timeout: 5s
            retries: 5

    postgres-slave1:
        image: postgres:17
        container_name: postgres-slave1
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - "5533:5432"
        volumes:
            - postgres-slave1-data:/var/lib/postgresql/data
            - ./slave/setup-slave.sh:/docker-entrypoint-initdb.d/setup-slave.sh
        depends_on:
            postgres-master:
                condition: service_healthy
        command: bash -c "chmod +x /docker-entrypoint-initdb.d/setup-slave.sh && /docker-entrypoint-initdb.d/setup-slave.sh"
        networks:
            - postgres-network

    postgres-slave2:
        image: postgres:17
        container_name: postgres-slave2
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - "5534:5432"
        volumes:
            - postgres-slave2-data:/var/lib/postgresql/data
            - ./slave/setup-slave.sh:/docker-entrypoint-initdb.d/setup-slave.sh
        depends_on:
            postgres-master:
                condition: service_healthy
        command: bash -c "chmod +x /docker-entrypoint-initdb.d/setup-slave.sh && /docker-entrypoint-initdb.d/setup-slave.sh"
        networks:
            - postgres-network

volumes:
    postgres-master-data:
    postgres-slave1-data:
    postgres-slave2-data:


networks:
    postgres-network:
        driver: bridge
